language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e $TRAVIS_BUILD_DIR
#  - python ./lowkey-examples/setup.py install
#  - python ./setup.py sdist

addons:
  sonarcloud:
    organization: "david-istvan"

script:
  - pytest ./lowkey/lww/tests/TestSuite.py
  - pytest ./lowkey/collabtypes/tests/TestSuite.py
  - pytest ./lowkey-examples/mindmap/tests/TestSuite.py
  - sonar-scanner
