name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install -e $GITHUB_WORKSPACE
      - name: Unit tests
        run: |
          pytest ./lowkey/lww/tests/TestSuite.py
          pytest ./lowkey/collabtypes/tests/TestSuite.py
          pytest ./lowkey/collabapi/tests/TestSuite.py
          pytest ./lowkey-examples/mindmap/tests/TestSuite.py
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}